In [1]:
import numpy as np
import pandas as pd
import warnings
import matplotlib.pyplot as plt
import seaborn as sns
import math
import datetime

%matplotlib inline
%run function.ipynb

In [2]:
data = pd.read_csv('model1.csv')
data = data.dropna()
data = data.drop(['DisbursePerMonth', 'DisbursePerEmployee'], axis=1)
data

State   Term  NoEmp  NewExist  IsFranchised  UrbanRural  RevLineCr  \
0         NC  162.0    2.0       0.0           1.0           1        0.0   
1         AR  126.0    7.0       1.0           0.0           1        0.0   
2         CA   83.0   18.0       0.0           0.0           1        1.0   
3         FL   84.0    4.0       1.0           0.0           1        1.0   
4         LA   60.0    3.0       1.0           0.0           1        0.0   
...      ...    ...    ...       ...           ...         ...        ...   
518436    CO   84.0    2.0       1.0           0.0           0        1.0   
518437    AZ   29.0    2.0       0.0           0.0           1       -1.0   
518438    NV  240.0   20.0       1.0           0.0           1       -1.0   
518439    AZ   84.0    3.0       1.0           0.0           1        1.0   
518440    IL  240.0   10.0       1.0           0.0           1       -1.0   

        LowDoc  DisbursementGross  Default         Industry  Bank%  \
0          0.0       3.071757e+05      0.0     Retail_trade   25.0   
1          0.0       1.664374e+05      0.0  Accom/Food_serv   15.0   
2          0.0       5.316067e+05      0.0      Educational   50.0   
3          0.0       6.235643e+04      0.0     Construction   50.0   
4          0.0       6.061084e+04      0.0  RE/Rental/Lease   15.0   
...        ...                ...      ...              ...    ...   
518436     0.0       3.636650e+04      0.0      Educational   50.0   
518437     0.0       2.060768e+05      1.0     Other_no_pub   25.0   
518438     0.0       6.170183e+05      0.0     Construction    0.0   
518439     0.0       1.895301e+04      0.0      Information   50.0   
518440     0.0       1.258281e+06      0.0  Accom/Food_serv    0.0   

       State_division  Is_Cross_State  Appv_Dusburse_delta  RealEstate  \
0          South East               1                 52.0         0.0   
1          South East               1                 82.0         0.0   
2                West               1                 21.0         0.0   
3          South East               0                 21.0         0.0   
4          South East               0                113.0         0.0   
...               ...             ...                  ...         ...   
518436     South West               1                 22.0         0.0   
518437     South West               1                 22.0         0.0   
518438           West               0                464.0         1.0   
518439     South West               1                 22.0         0.0   
518440       Mid-West               0                 65.0         1.0   

        Recession  Mon_Is_14710  rate  
0             0.0           0.0  4.47  
1             0.0           1.0  4.47  
2             0.0           0.0  4.47  
3             0.0           0.0  4.47  
4             0.0           0.0  4.47  
...           ...           ...   ...  
518436        0.0           0.0  4.51  
518437        0.0           0.0  4.51  
518438        0.0           0.0  4.51  
518439        0.0           0.0  4.51  
518440        0.0           1.0  4.51  

[518441 rows x 19 columns]

In [3]:
y = data['Default']
X = data.drop('Default', axis=1)

In [4]:
X.columns

Index(['State', 'Term', 'NoEmp', 'NewExist', 'IsFranchised', 'UrbanRural',
       'RevLineCr', 'LowDoc', 'DisbursementGross', 'Industry', 'Bank%',
       'State_division', 'Is_Cross_State', 'Appv_Dusburse_delta', 'RealEstate',
       'Recession', 'Mon_Is_14710', 'rate'],
      dtype='object')

In [5]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score

In [6]:
X_dum = pd.get_dummies(X, columns=['State', 'Industry', 'State_division'], dtype=np.float64)

In [7]:
X_dum

Term  NoEmp  NewExist  IsFranchised  UrbanRural  RevLineCr  LowDoc  \
0       162.0    2.0       0.0           1.0           1        0.0     0.0   
1       126.0    7.0       1.0           0.0           1        0.0     0.0   
2        83.0   18.0       0.0           0.0           1        1.0     0.0   
3        84.0    4.0       1.0           0.0           1        1.0     0.0   
4        60.0    3.0       1.0           0.0           1        0.0     0.0   
...       ...    ...       ...           ...         ...        ...     ...   
518436   84.0    2.0       1.0           0.0           0        1.0     0.0   
518437   29.0    2.0       0.0           0.0           1       -1.0     0.0   
518438  240.0   20.0       1.0           0.0           1       -1.0     0.0   
518439   84.0    3.0       1.0           0.0           1        1.0     0.0   
518440  240.0   10.0       1.0           0.0           1       -1.0     0.0   

        DisbursementGross  Bank%  Is_Cross_State  ...  Industry_Unknown  \
0            3.071757e+05   25.0               1  ...               0.0   
1            1.664374e+05   15.0               1  ...               0.0   
2            5.316067e+05   50.0               1  ...               0.0   
3            6.235643e+04   50.0               0  ...               0.0   
4            6.061084e+04   15.0               0  ...               0.0   
...                   ...    ...             ...  ...               ...   
518436       3.636650e+04   50.0               1  ...               0.0   
518437       2.060768e+05   25.0               1  ...               0.0   
518438       6.170183e+05    0.0               0  ...               0.0   
518439       1.895301e+04   50.0               1  ...               0.0   
518440       1.258281e+06    0.0               0  ...               0.0   

        Industry_Utilities  Industry_Wholesale_trade  \
0                      0.0                       0.0   
1                      0.0                       0.0   
2                      0.0                       0.0   
3                      0.0                       0.0   
4                      0.0                       0.0   
...                    ...                       ...   
518436                 0.0                       0.0   
518437                 0.0                       0.0   
518438                 0.0                       0.0   
518439                 0.0                       0.0   
518440                 0.0                       0.0   

        State_division_Mid-Atlantic  State_division_Mid-West  \
0                               0.0                      0.0   
1                               0.0                      0.0   
2                               0.0                      0.0   
3                               0.0                      0.0   
4                               0.0                      0.0   
...                             ...                      ...   
518436                          0.0                      0.0   
518437                          0.0                      0.0   
518438                          0.0                      0.0   
518439                          0.0                      0.0   
518440                          0.0                      1.0   

        State_division_North East  State_division_North West  \
0                             0.0                        0.0   
1                             0.0                        0.0   
2                             0.0                        0.0   
3                             0.0                        0.0   
4                             0.0                        0.0   
...                           ...                        ...   
518436                        0.0                        0.0   
518437                        0.0                        0.0   
518438                        0.0                        0.0   
518439                        0.0                        0.0   
518440       

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X_dum, y, random_state=0, test_size=0.25)

forest = RandomForestClassifier()

print('start:', datetime.datetime.now())
forest.fit(X_train, y_train)
y_pred = forest.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print('CV:', np.mean(cross_val_score(forest, X_train, y_train.values.ravel())))
print("Accuracy: ", acc)
print('end:', datetime.datetime.now())

from sklearn import metrics
confusion_matrix = metrics.confusion_matrix(y_test, y_pred, labels=[1, 0])
print('Confusion Matrix :')
print(confusion_matrix)
print('recall_score:', metrics.recall_score(y_test, y_pred, zero_division=0))
print('f_score:', metrics.f1_score(y_test, y_pred, zero_division=0))
print('precision_score:', metrics.precision_score(y_test, y_pred, zero_division=0))

start: 2021-09-20 12:40:22.239193
CV: 0.9291284108736464
Accuracy:  0.9296201711274507
end: 2021-09-20 12:47:37.173547
Confusion Matrix :
[[27021  6534]
 [ 2588 93468]]
recall_score: 0.805274921770228
f_score: 0.8555822937116079
precision_score: 0.912594143672532


In [9]:
d = {'feature': X_dum.columns, 'importance': forest.feature_importances_}
display(pd.DataFrame(data=d).sort_values(by=['importance'], ascending=False).iloc[:20, :])

feature  importance
0                          Term    0.456056
7             DisbursementGross    0.086186
14                         rate    0.080068
10          Appv_Dusburse_delta    0.070265
1                         NoEmp    0.040634
9                Is_Cross_State    0.031287
8                         Bank%    0.025641
5                     RevLineCr    0.019809
11                   RealEstate    0.013070
13                 Mon_Is_14710    0.010038
2                      NewExist    0.008926
4                    UrbanRural    0.007542
82        Industry_Retail_trade    0.005738
66     Industry_Accom/Food_serv    0.005059
6                        LowDoc    0.004962
78        Industry_Other_no_pub    0.004562
91    State_division_South East    0.004358
89    State_division_North East    0.004344
19                     State_CA    0.004300
87  State_division_Mid-Atlantic    0.004236

In [10]:
display(pd.DataFrame(data=d).sort_values(by=['importance'], ascending=False).iloc[20:40, :])

feature  importance
70              Industry_Construction    0.004167
93                State_division_West    0.004055
75             Industry_Manufacturing    0.003992
79         Industry_Prof/Science/Tech    0.003838
73  Industry_Healthcare/Social_assist    0.003783
3                        IsFranchised    0.003733
86           Industry_Wholesale_trade    0.003585
88            State_division_Mid-West    0.003542
92          State_division_South West    0.003124
67  Industry_Admin_sup/Waste_Mgmt_Rem    0.003051
49                           State_NY    0.002915
83                Industry_Trans/Ware    0.002875
53                           State_PA    0.002654
84                   Industry_Unknown    0.002605
24                           State_FL    0.002588
29                           State_IL    0.002486
12                          Recession    0.002480
58                           State_TX    0.002421
46                           State_NJ    0.002298
50                           State_OH    0.002289

In [11]:
display(pd.DataFrame(data=d).sort_values(by=['importance'], ascending=False).iloc[40:60, :])

feature  importance
69  Industry_Arts/Entertain/Rec    0.001914
81     Industry_RE/Rental/Lease    0.001899
90    State_division_North West    0.001781
59                     State_UT    0.001780
37                     State_MI    0.001721
38                     State_MN    0.001684
63                     State_WI    0.001669
25                     State_GA    0.001616
74         Industry_Information    0.001555
72   Industry_Finance/Insurance    0.001506
39                     State_MO    0.001488
18                     State_AZ    0.001325
30                     State_IN    0.001319
20                     State_CO    0.001274
34                     State_MA    0.001255
60                     State_VA    0.001234
42                     State_NC    0.001188
71         Industry_Educational    0.001183
62                     State_WA    0.001138
35                     State_MD    0.001124

In [12]:
display(pd.DataFrame(data=d).sort_values(by=['importance'], ascending=False).iloc[60:80:])

feature  importance
21                   State_CT    0.001046
68  Industry_Ag/For/Fish/Hunt    0.001011
32                   State_KY    0.000996
31                   State_KS    0.000995
27                   State_IA    0.000965
51                   State_OK    0.000883
57                   State_TN    0.000882
41                   State_MT    0.000848
45                   State_NH    0.000830
28                   State_ID    0.000791
40                   State_MS    0.000777
36                   State_ME    0.000758
48                   State_NV    0.000729
52                   State_OR    0.000729
33                   State_LA    0.000719
44                   State_NE    0.000698
54                   State_RI    0.000674
16                   State_AL    0.000645
43                   State_ND    0.000633
17                   State_AR    0.000612

In [13]:
display(pd.DataFrame(data=d).sort_values(by=['importance'], ascending=False).iloc[80:, :])

feature  importance
55                       State_SC    0.000576
47                       State_NM    0.000572
26                       State_HI    0.000494
61                       State_VT    0.000427
23                       State_DE    0.000421
64                       State_WV    0.000376
56                       State_SD    0.000375
65                       State_WY    0.000295
77  Industry_Min/Quar/Oil_Gas_ext    0.000292
15                       State_AK    0.000283
22                       State_DC    0.000262
85             Industry_Utilities    0.000113
80          Industry_Public_Admin    0.000050
76             Industry_Mgmt_comp    0.000035

In [14]:
X = X.drop('State', axis=1)
X_dum = pd.get_dummies(X, columns=['Industry', 'State_division'], dtype=np.float64)

X_train, X_test, y_train, y_test = train_test_split(X_dum, y, random_state=0, test_size=0.25)

forest = RandomForestClassifier()

print('start:', datetime.datetime.now())
forest.fit(X_train, y_train)
y_pred = forest.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print('CV:', np.mean(cross_val_score(forest, X_train, y_train.values.ravel())))
print("Accuracy: ", acc)
print('end:', datetime.datetime.now())

from sklearn import metrics
confusion_matrix = metrics.confusion_matrix(y_test, y_pred, labels=[1, 0])
print('Confusion Matrix :')
print(confusion_matrix)
print('recall_score:', metrics.recall_score(y_test, y_pred, zero_division=0))
print('f_score:', metrics.f1_score(y_test, y_pred, zero_division=0))
print('precision_score:', metrics.precision_score(y_test, y_pred, zero_division=0))

start: 2021-09-20 12:47:38.829675
CV: 0.9314867679962966
Accuracy:  0.9316956122551326
end: 2021-09-20 12:52:48.463379
Confusion Matrix :
[[27479  6076]
 [ 2777 93279]]
recall_score: 0.8189241543734168
f_score: 0.8612621648305151
precision_score: 0.9082165520888419


In [15]:
d = {'feature': X_dum.columns, 'importance': forest.feature_importances_}
display(pd.DataFrame(data=d).sort_values(by=['importance'], ascending=False))

feature  importance
0                                Term    0.491501
7                   DisbursementGross    0.091948
14                               rate    0.083439
10                Appv_Dusburse_delta    0.072053
1                               NoEmp    0.040841
9                      Is_Cross_State    0.031205
8                               Bank%    0.025351
5                           RevLineCr    0.019467
11                         RealEstate    0.015064
13                       Mon_Is_14710    0.009478
2                            NewExist    0.008768
4                          UrbanRural    0.007693
42                State_division_West    0.007639
36        State_division_Mid-Atlantic    0.007028
40          State_division_South East    0.006601
38          State_division_North East    0.006041
37            State_division_Mid-West    0.005913
31              Industry_Retail_trade    0.005474
6                              LowDoc    0.005033
41          State_division_South West    0.004952
15           Industry_Accom/Food_serv    0.004790
27              Industry_Other_no_pub    0.004435
19              Industry_Construction    0.004026
24             Industry_Manufacturing    0.003896
3                        IsFranchised    0.003721
22  Industry_Healthcare/Social_assist    0.003680
28         Industry_Prof/Science/Tech    0.003676
35           Industry_Wholesale_trade    0.003468
39          State_division_North West    0.002937
16  Industry_Admin_sup/Waste_Mgmt_Rem    0.002926
32                Industry_Trans/Ware    0.002819
33                   Industry_Unknown    0.002442
12                          Recession    0.002310
18        Industry_Arts/Entertain/Rec    0.001883
30           Industry_RE/Rental/Lease    0.001810
23               Industry_Information    0.001500
21         Industry_Finance/Insurance    0.001439
20               Industry_Educational    0.001133
17          Industry_Ag/For/Fish/Hunt    0.001092
26      Industry_Min/Quar/Oil_Gas_ext    0.000331
34                 Industry_Utilities    0.000114
29              Industry_Public_Admin    0.000046
25                 Industry_Mgmt_comp    0.000035

In [16]:
X = X.drop('Industry', axis=1)
X_dum = pd.get_dummies(X, columns=['State_division'], dtype=np.float64)

X_train, X_test, y_train, y_test = train_test_split(X_dum, y, random_state=0, test_size=0.25)

forest = RandomForestClassifier()

print('start:', datetime.datetime.now())
forest.fit(X_train, y_train)
y_pred = forest.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print('CV:', np.mean(cross_val_score(forest, X_train, y_train.values.ravel())))
print("Accuracy: ", acc)
print('end:', datetime.datetime.now())

from sklearn import metrics
confusion_matrix = metrics.confusion_matrix(y_test, y_pred, labels=[1, 0])
print('Confusion Matrix :')
print(confusion_matrix)
print('recall_score:', metrics.recall_score(y_test, y_pred, zero_division=0))
print('f_score:', metrics.f1_score(y_test, y_pred, zero_division=0))
print('precision_score:', metrics.precision_score(y_test, y_pred, zero_division=0))

start: 2021-09-20 12:52:49.711786
CV: 0.9346501041586297
Accuracy:  0.9353064168936278
end: 2021-09-20 12:56:59.804728
Confusion Matrix :
[[27963  5592]
 [ 2793 93263]]
recall_score: 0.8333482342422888
f_score: 0.8696179502728927
precision_score: 0.9091884510339446


In [17]:
d = {'feature': X_dum.columns, 'importance': forest.feature_importances_}
display(pd.DataFrame(data=d).sort_values(by=['importance'], ascending=False))

feature  importance
0                          Term    0.527347
7             DisbursementGross    0.097164
14                         rate    0.090009
10          Appv_Dusburse_delta    0.074801
1                         NoEmp    0.041365
9                Is_Cross_State    0.033369
8                         Bank%    0.026278
5                     RevLineCr    0.019978
11                   RealEstate    0.013847
13                 Mon_Is_14710    0.008516
2                      NewExist    0.008418
21          State_division_West    0.008082
4                    UrbanRural    0.007526
15  State_division_Mid-Atlantic    0.006683
17    State_division_North East    0.006446
19    State_division_South East    0.006294
16      State_division_Mid-West    0.005527
6                        LowDoc    0.004927
20    State_division_South West    0.004761
3                  IsFranchised    0.003927
18    State_division_North West    0.002691
12                    Recession    0.002045

In [22]:
X = X.drop('Recession', axis=1)
X_dum = pd.get_dummies(X, columns=['State_division'], dtype=np.float64)

X_train, X_test, y_train, y_test = train_test_split(X_dum, y, random_state=0, test_size=0.25)

forest = RandomForestClassifier()

print('start:', datetime.datetime.now())
forest.fit(X_train, y_train)
y_pred = forest.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print('CV:', np.mean(cross_val_score(forest, X_train, y_train.values.ravel())))
print("Accuracy: ", acc)
print('end:', datetime.datetime.now())

from sklearn import metrics
confusion_matrix = metrics.confusion_matrix(y_test, y_pred, labels=[1, 0])
print('Confusion Matrix :')
print(confusion_matrix)
print('recall_score:', metrics.recall_score(y_test, y_pred, zero_division=0))
print('f_score:', metrics.f1_score(y_test, y_pred, zero_division=0))
print('precision_score:', metrics.precision_score(y_test, y_pred, zero_division=0))

start: 2021-09-20 14:02:10.119154
CV: 0.9351413214000978
Accuracy:  0.9354375786005817
end: 2021-09-20 14:06:16.618573
Confusion Matrix :
[[28008  5547]
 [ 2821 93235]]
recall_score: 0.8346893160482789
f_score: 0.8700298210735586
precision_score: 0.9084952479807973


# RF tune parameter

In [18]:
from sklearn.model_selection import KFold, GridSearchCV, RandomizedSearchCV

In [24]:
print('start:', datetime.datetime.now())
forest_t = RandomForestClassifier()

# 設定要訓練的超參數組合
n_estimators = [500, 900, 1200, 1500, 1800, 2500, 3000]
max_depth = [1, 4, 6, 8, 10]
param_grid = dict(n_estimators=n_estimators, max_depth=max_depth)

## 建立搜尋物件，放入模型及參數組合字典 (n_jobs=-1 會使用全部 cpu 平行運算)
grid_search = GridSearchCV(forest_t, param_grid, scoring='f1', n_jobs=-1, verbose=1, cv=3)

# 開始搜尋最佳參數
grid_result = grid_search.fit(X_train, y_train)

# 印出最佳結果與最佳參數
print("Best f1_score: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

print(grid_result.best_params_)
print('end:', datetime.datetime.now())

start: 2021-09-20 22:12:28.241728
Fitting 3 folds for each of 35 candidates, totalling 105 fits
Best f1_score: 0.810504 using {'max_depth': 10, 'n_estimators': 1200}
{'max_depth': 10, 'n_estimators': 1200}
end: 2021-09-20 23:56:27.599943


In [25]:
forest_bestparam = RandomForestClassifier(max_depth=grid_result.best_params_['max_depth'], 
                                          n_estimators=grid_result.best_params_['n_estimators'])

# 訓練模型
forest_bestparam.fit(X_train, y_train)

# 預測測試集
y_pred = forest_bestparam.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print('CV:', np.mean(cross_val_score(forest_bestparam, X_train, y_train.values.ravel())))
print("Accuracy: ", acc)

confusion_matrix = metrics.confusion_matrix(y_test, y_pred, labels=[1, 0])
print('Confusion Matrix :')
print(confusion_matrix)
print('recall_score:', metrics.recall_score(y_test, y_pred, zero_division=0))
print('f_score:', metrics.f1_score(y_test, y_pred, zero_division=0))
print('precision_score:', metrics.precision_score(y_test, y_pred, zero_division=0))

CV: 0.9082812540184657
Accuracy:  0.9072532423945499
Confusion Matrix :
[[25228  8327]
 [ 3694 92362]]
recall_score: 0.7518402622559976
f_score: 0.8075931942955007
precision_score: 0.8722771592559297


max_depth不設限於10(random)

In [23]:
print('start:', datetime.datetime.now())
forest_t = RandomForestClassifier()

# 設定要訓練的超參數組合
distribution = {'n_estimators': range(300, 2000), 'max_depth': range(6, 35)}

## 建立搜尋物件，放入模型及參數組合字典 (n_jobs=-1 會使用全部 cpu 平行運算)
random_search = RandomizedSearchCV(forest_t, distribution, scoring='f1', n_jobs=-1, verbose=1, cv=3, n_iter=20)

# 開始搜尋最佳參數
random_result = random_search.fit(X_train, y_train)

# 印出最佳結果與最佳參數
print("Best f1_score: %f using %s" % (random_result.best_score_, random_result.best_params_))

print(random_result.best_params_)
print('end:', datetime.datetime.now())

forest_bestparam_rd = RandomForestClassifier(max_depth=random_result.best_params_['max_depth'], 
                                          n_estimators=random_result.best_params_['n_estimators'])

# 訓練模型
forest_bestparam_rd.fit(X_train, y_train)

# 預測測試集
y_pred = forest_bestparam_rd.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print('CV:', np.mean(cross_val_score(forest_bestparam_rd, X_train, y_train.values.ravel())))
print("Accuracy: ", acc)

confusion_matrix = metrics.confusion_matrix(y_test, y_pred, labels=[1, 0])
print('Confusion Matrix :')
print(confusion_matrix)
print('recall_score:', metrics.recall_score(y_test, y_pred, zero_division=0))
print('f_score:', metrics.f1_score(y_test, y_pred, zero_division=0))
print('precision_score:', metrics.precision_score(y_test, y_pred, zero_division=0))

start: 2021-09-20 16:47:46.526867
Fitting 3 folds for each of 20 candidates, totalling 60 fits


D:\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:918: UserWarning: One or more of the test scores are non-finite: [0.79450132 0.84752414 0.85865421 0.82846652 0.82848744 0.86883935
 0.86478296 0.86880402 0.86555063 0.86727034 0.85925395 0.71567099
 0.84730536 0.81989581 0.86876223        nan        nan 0.83591548
        nan        nan]
  warnings.warn(


Best f1_score: 0.868839 using {'n_estimators': 866, 'max_depth': 28}
{'n_estimators': 866, 'max_depth': 28}
end: 2021-09-20 17:59:43.414763
CV: 0.935815137720855
Accuracy:  0.9358773560886036
Confusion Matrix :
[[28087  5468]
 [ 2843 93213]]
recall_score: 0.8370436596632395
f_score: 0.8711173141040552
precision_score: 0.9080827675396056
